
package clink;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class clinkSettings extends javax.swing.JFrame {

    private Pattern pattern = Pattern.compile("-?\\d+(\\.\\d+)?");
    String priceLevel = null;
    String timeLimit = null;
    String bidOn, newConfig = null;
    //String filePath = "/home/alvo/Desktop/clink.txt";
    String filePath = "clink.txt";
    
    public clinkSettings() {
        
       super("Settings");

        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent we) {
                int result = JOptionPane.showConfirmDialog(null, "Do you want to Exit ?", "Exit Confirmation : ",
                        JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                } else if (result == JOptionPane.NO_OPTION) {
                    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                }
            }
        });
        setUndecorated(true);
        pack();
        java.awt.Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int height = screenSize.height;
        int width = screenSize.width;
        setSize(width / 3, height / 2);

        // here's the part where i center the jframe on screen
        setLocationRelativeTo(null);
        setVisible(true);
       
        initComponents();
        
        
         File fl=new File(filePath);
        int i = 0;
        Scanner scan=null;
        try {
           scan=new Scanner(fl);
           scan.useDelimiter(", *");
           while (scan.hasNext())  { 
              String config = scan.next();
               if (i == 0){
                   settings_priceLevel.setSelectedItem(config);
               }else if (i == 1){
                   settings_timeLimit.setText(config);
               }else if (i == 2){
                   if(config.equals("All")){
                      radioAll.setSelected(true);                                     
                      System.out.println(config+"1 \n");
                   }else if (config.equals("Latest")){
                      radioLatest.setSelected(true);
                      System.out.println(config+"1 \n");
                   }
               }
               
               //radioAll.setSelected(true);
               i++;
            }   
        } catch (FileNotFoundException ex) {
            
            //config file is not there
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settings_bidOn = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        settings_btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        settings_timeLimit = new javax.swing.JTextField();
        settings_priceLevel = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        radioLatest = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        radioAll = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        settings_btnSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(478, 300));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(28, 39, 84));

        jPanel2.setBackground(new java.awt.Color(19, 28, 59));
        jPanel2.setPreferredSize(new java.awt.Dimension(478, 300));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Price Level");

        settings_btnBack.setBackground(new java.awt.Color(28, 39, 84));
        settings_btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        settings_btnBack.setForeground(new java.awt.Color(255, 255, 255));
        settings_btnBack.setText("BACK");
        settings_btnBack.setBorderPainted(false);
        settings_btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settings_btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Refresh after:");

        settings_timeLimit.setBackground(new java.awt.Color(19, 28, 59));
        settings_timeLimit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        settings_timeLimit.setForeground(new java.awt.Color(0, 204, 0));
        settings_timeLimit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 0, 213)));
        settings_timeLimit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        settings_priceLevel.setBackground(new java.awt.Color(19, 28, 59));
        settings_priceLevel.setForeground(new java.awt.Color(244, 244, 244));
        settings_priceLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Minimum", "Average", "Maximum" }));
        settings_priceLevel.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bid on:");

        radioLatest.setBackground(new java.awt.Color(28, 39, 84));
        settings_bidOn.add(radioLatest);
        radioLatest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioLatest.setForeground(new java.awt.Color(255, 255, 255));
        radioLatest.setText("Latest");
        radioLatest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLatestActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("(Prev bids remain on page after refresh)");

        radioAll.setBackground(new java.awt.Color(28, 39, 84));
        settings_bidOn.add(radioAll);
        radioAll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioAll.setForeground(new java.awt.Color(255, 255, 255));
        radioAll.setText("All");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("(Remove order from auction page after bid to bid the rest in the page)");

        settings_btnSave.setBackground(new java.awt.Color(28, 39, 84));
        settings_btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        settings_btnSave.setForeground(new java.awt.Color(255, 255, 255));
        settings_btnSave.setText("SAVE CHANGES");
        settings_btnSave.setBorderPainted(false);
        settings_btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settings_btnSaveActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(28, 39, 84));
        btnExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("X");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(settings_priceLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(settings_timeLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(settings_btnSave)
                        .addGap(63, 63, 63)
                        .addComponent(settings_btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(radioAll)
                    .addComponent(radioLatest)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(settings_timeLimit)
                    .addComponent(settings_priceLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioLatest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settings_btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settings_btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settings_btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settings_btnBackActionPerformed
        new clinkLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_settings_btnBackActionPerformed

    private void radioLatestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLatestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioLatestActionPerformed

    private void settings_btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settings_btnSaveActionPerformed
        String priceLevel = settings_priceLevel.getSelectedItem().toString();
        String timeLimit = settings_timeLimit.getText().toString();
        String bidOn = null;
        if(radioLatest.isSelected()){
            bidOn = radioLatest.getText();
        }else if (radioAll.isSelected()){
            bidOn = radioAll.getText();
        }else{
            JOptionPane.showMessageDialog(null, "Please select All or Latest bids");
        }
        boolean isNumber = pattern.matcher(timeLimit).matches();
       
        newConfig = priceLevel+", "+timeLimit+", "+bidOn;
        
        if (timeLimit.equals("")) {
            JOptionPane.showMessageDialog(null, "Add A Time Limit");
        } else if (isNumber = false) {
            JOptionPane.showMessageDialog(null, "Invalid Email");
        } else {
            try { 
            FileWriter myWriter = new FileWriter(filePath);
            myWriter.write(newConfig);
            myWriter.close();
            JOptionPane.showMessageDialog(null, "Configuration Successfully changed");
            new clinkLogin().setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(clinkSettings.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_settings_btnSaveActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Do you want to Exit ?", "Exit Confirmation : ",
            JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.YES_OPTION) {
            setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } else if (result == JOptionPane.NO_OPTION) {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clinkSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clinkSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clinkSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clinkSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clinkSettings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton radioAll;
    private javax.swing.JRadioButton radioLatest;
    private javax.swing.ButtonGroup settings_bidOn;
    private javax.swing.JButton settings_btnBack;
    private javax.swing.JButton settings_btnSave;
    private javax.swing.JComboBox<String> settings_priceLevel;
    private javax.swing.JTextField settings_timeLimit;
    // End of variables declaration//GEN-END:variables
}
